ABSM/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ABSM.Models
{
    public class Order
    {
        [Key]
        public int OrderId { get; set; }

        [DataType(DataType.DateTime)]
        public DateTime OrderDate { get; set; }

        [Required]
        public string TransactionId { get; set; }
        
        [Required]
        [StringLength(160)]
        public string FullName { get; set; }

        [Required]
        [StringLength(70, MinimumLength = 3)]
        public string Address { get; set; }

        [Required]
        [StringLength(40)]
        public string City { get; set; }

        [Required]
        [StringLength(40)]
        public string State { get; set; }

        [Required]
        [StringLength(10, MinimumLength = 5)]
        public string PostalCode { get; set; }

        [Required]
        [StringLength(40)]
        public string Country { get; set; }

        [Required]
        [StringLength(24)]
        public string Phone { get; set; }

        [Required]
        public string Email { get; set; }

        public string  UserId { get; set; }

        [Required]
        public decimal Total { get; set; }

        public string PaymentMode  { get; set; }

        public virtual List<OrderDetail> OrderDetails { get; set; }

        public Order()
        {
            OrderDetails = new List<OrderDetail>();
        }
    }
}

ABSM/ViewModels/IncomeViewModel.cs
using ABSM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ABSM.ViewModels
{
    public class IncomeViewModel
    {
        public IEnumerable<OrderDetail> Items { get; set; }
        public decimal Total { get; set; }
      
    }
}

ABSM/ViewModels/OrdersViewModel.cs
using ABSM.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ABSM.ViewModels
{
    public class OrdersViewModel
    {
        public IEnumerable<Order> Orders { get; set; }
        public IEnumerable<OrderDetail> OrderDetails { get; set; }


    }
}

ABSM/Areas/Admin/Controllers/OwnerController.cs
using ABSM.Models;
using ABSM.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace ABSM.Areas.Admin.Controllers
{
    [Authorize(Roles = "Shop")]
    public class OwnerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        public ActionResult Index()
        {
            int shopid = Convert.ToInt32(Session["Shop"].ToString());
            var complains = db.Complains.Include("Shop").Where(c => c.ShopID == shopid);
            return View(complains);
        }

        
        #region Products
        // GET: Admin/Products
        public ActionResult ListProducts()
        {
            int shopid = Convert.ToInt32(Session["Shop"].ToString());
            var products = db.Products.Include("Shop").Include("Category").Where(p=>p.ShopID==shopid);
            return View(products.ToList());
        }


       

        // GET: Admin/Products/Details/5
        public ActionResult PDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }



        // GET: Admin/Products/Create
        public ActionResult PCreate()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PCreate(Product product, HttpPostedFileBase doc)
        {
            string path;
            if (doc != null)
            {

                var filename = Path.GetFileName(doc.FileName);
                var extension = Path.GetExtension(filename).ToLower();
                if (extension == ".jpg" || extension == ".png" || extension == ".jpeg")
                {
                    path = HostingEnvironment.MapPath(Path.Combine("~/Content/Images/", filename));
                    doc.SaveAs(path);
                    product.ImageUrl = "~/Content/Images/" + filename;
                }
                else
                {
                    ModelState.AddModelError("", "Document size must be less then 5MB");
                    return View(product);
                }
                if (ModelState.IsValid)
                {
                    product.ShopID= Convert.ToInt32(Session["Shop"].ToString());
                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("ListProducts");
                }


            }
            ModelState.AddModelError("", "Please upload image");
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Admin/Products/Edit/5
        public ActionResult PEdit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Include("Category").Include("Shop").Where(x=>x.ProductID==id).SingleOrDefault();
            if (product == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            return View(product);
        }

        // POST: Admin/Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PEdit(Product product, string ImageValue, HttpPostedFileBase doc)
        {
            string path;
            if (doc != null && ModelState.IsValid)
            {

                var filename = Path.GetFileName(doc.FileName);
                var extension = Path.GetExtension(filename).ToLower();
                if (extension == ".jpg" || extension == ".png" || extension == ".jpeg")
                {
                    path = HostingEnvironment.MapPath(Path.Combine("~/Content/Images/", filename));
                    doc.SaveAs(path);
                    product.ImageUrl = "~/Content/Images/" + filename;
                    product.ShopID = Convert.ToInt32(Session["Shop"].ToString());
                    db.Entry(product).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("ListProducts");
                }
                else
                {
                    ModelState.AddModelError("", "Only Image Allowed");
                    return View(product);
                }
               
            }
            else if (ModelState.IsValid)
            {
                product.ImageUrl = ImageValue;
                db.Entry(product).State = EntityState.Modified;
                product.ShopID = Convert.ToInt32(Session["Shop"].ToString());
                db.SaveChanges();
                return RedirectToAction("ListProducts");

            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "Name", product.CategoryID);
            return View(product);
        }

        // GET: Admin/Products/Delete/5
        public ActionResult PDelete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Include("Category").Include("Shop").Where(x => x.ProductID == id).SingleOrDefault();
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Admin/Products/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PDeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            db.Products.Remove(product);
            db.SaveChanges();
            return RedirectToAction("ListProducts");
        }
        #endregion

        #region Categories
        public ActionResult ListCategories()
        {
            int shopid = Convert.ToInt32(Session["Shop"].ToString());
            var products = db.Categories.Include("Shop").Where(p => p.ShopID == shopid);
            return View(products.ToList());
        }
        public ActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Category category)
        {
            if (ModelState.IsValid)
            {   category.ShopID= Convert.ToInt32(Session["Shop"].ToString());
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }



        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            ViewBag.ShopID = new SelectList(db.Shops, "ShopID", "Name", category.ShopID);
            return View(category);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category category)
        {
            if (ModelState.IsValid)
            {
                category.ShopID= Convert.ToInt32(Session["Shop"].ToString());
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ShopID = new SelectList(db.Shops, "ShopID", "Name", category.ShopID);
            return View(category);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Admin/Categories/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        #endregion

        #region Orders
        public ActionResult ListOrders()
        {
            int shopid = Convert.ToInt32(Session["Shop"].ToString());
            var orderDetails = db.OrderDetails.Where(p => p.Product.ShopID == shopid).Include("Order").ToList();
            return View(orderDetails);
        }


        public ActionResult Order(int? id)
        {

            var order = db.Orders.Where(o => o.OrderId == id).SingleOrDefault();
            return View(order);
        }


        public ActionResult Income()
        {
            int shopid = Convert.ToInt32(Session["Shop"].ToString());
            var orderDetails = db.OrderDetails.Where(p => p.Product.ShopID == shopid).ToList();
            var result = new IncomeViewModel
            {
                Items = orderDetails,
                Total = Calcuate(orderDetails),
            };
            return View(result);
        }
        [HttpPost]
        public ActionResult Income(int? Month)

ABSM/Areas/Admin/Views/Owner/Create.cshtml
@model ABSM.Models.Category

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ABSM/Areas/Admin/Views/Owner/Delete.cshtml
@model ABSM.Models.Category

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Shop.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shop.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ABSM/Areas/Admin/Views/Owner/Edit.cshtml
@model ABSM.Models.Category

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Category</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShopID, "ShopID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ShopID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ShopID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListCategories")
</div>

ABSM/Areas/Admin/Views/Owner/Income.cshtml
@model ABSM.ViewModels.IncomeViewModel
@{
    ViewBag.Title = "Income";
}

<h2>Income</h2>
<h3>@ViewBag.Message</h3>
<form method="post">
    <label>Month</label>
    @Html.DropDownList("Month", new List<SelectListItem>
                        {
                            new SelectListItem{ Text="Select Month"},
                            new SelectListItem{ Text="January", Value = "1" },
                            new SelectListItem{ Text="February", Value = "2" },
                            new SelectListItem{ Text="March", Value = "3" },
                            new SelectListItem{ Text="April", Value = "4" },
                            new SelectListItem{ Text="May", Value = "5" },
                            new SelectListItem{ Text="June", Value = "6" },
                            new SelectListItem{ Text="July", Value = "7" },
                            new SelectListItem{ Text="August", Value = "8" },
                            new SelectListItem{ Text="September", Value = "9" },
                            new SelectListItem{ Text="October", Value = "10" },
                            new SelectListItem{ Text="November", Value = "11" },
                            new SelectListItem{ Text="December", Value = "12" },
                         
                         })
    <button type="submit"  class="btn btn-primary waves-effect waves-light" >Search</button>
</form>


    <!-- <div class="panel-heading">
        <h4>Invoice</h4>
    </div> -->
@if (Model != null)
{
    <div class="panel-body">
        <div class="clearfix">
            <div class="pull-left">
                <h3 class="logo">Monthly Income</h3>
            </div>
            
        </div>
        <hr>
        
        <!-- end row -->
   
        <div class="m-h-50"></div>
        <div class="row">
            <div class="col-xs-12">
                <div class="table-responsive">
                    <table class="table m-t-30">
                        <thead class="bg-faded">
                            <tr>
                                <th>#</th>
                                <th>Product </th>
                                <th>Quantity</th>
                                <th>Unit Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.Items)
                            {
                                int i = 0;
                                i = i + 1;
                                <tr>
                                    <th scope="row">@i</th>
                                    <td>@item.Product.Name</td>
                                    <td>@item.Quantity</td>
                                    <td>@item.UnitPrice</td>

                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="row">
            
            <div class="col-md-3 col-sm-6 col-xs-6 col-md-offset-3">
                
                <hr>
                <h3 class="text-xs-right">PKR @Model.Total</h3>
            </div>
        </div>
        <hr>
        <div class="hidden-print">
            <div class="pull-xs-right">
                <a href="javascript:window.print()" class="btn btn-dark waves-effect waves-light"><i class="fa fa-print"></i></a>
            </div>
            <div class="clearfix"></div>
        </div>
    
    </div>
}

ABSM/Areas/Admin/Views/Owner/Index.cshtml
@model IEnumerable<ABSM.Models.Complain>

@{
    ViewBag.Title = "Index";
}

<h2>Complains</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.TransactionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Shop.Name)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TransactionId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Shop.Name)
        </td>
       
    </tr>
}

</table>

ABSM/Areas/Admin/Views/Owner/ListCategories.cshtml
@model IEnumerable<ABSM.Models.Category>

@{
    ViewBag.Title = "Categories";
}

<h2>Categories</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Shop.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Shop.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CategoryID }) |
            @Html.ActionLink("Details", "Details", new { id=item.CategoryID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CategoryID })
        </td>
    </tr>
}

</table>

ABSM/Areas/Admin/Views/Owner/ListOrders.cshtml
@model IEnumerable<ABSM.Models.OrderDetail>

@{
    ViewBag.Title = "Orders";
}

<h2>Orders</h2>


<table class="table">
    <tr>
        <th>
            <label>Customer Name</label>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Order.TransactionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Product.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnitPrice)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Order.FullName, "Order", new { id=item.Order.OrderId})
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Order.TransactionId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Product.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnitPrice)
        </td>
        
    </tr>
}

</table>

ABSM/Areas/Admin/Views/Owner/PCreate.cshtml
@model ABSM.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("PCreate","Owner",FormMethod.Post,new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="doc" />
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LongDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LongDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LongDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListProducts")
</div>

ABSM/Areas/Admin/Views/Owner/PDelete.cshtml
@model ABSM.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Shop.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Shop.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImageUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImageUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShortDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShortDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LongDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LongDescription)
        </dd>

    </dl>

    @using (Html.BeginForm("PDeleteConfirmed", "Owner",FormMethod.Post)) {
        @Html.AntiForgeryToken()
        <input type="hidden" name="id" value='@Model.ProductID'/>
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "ListProducts")
        </div>
    }
</div>

ABSM/Areas/Admin/Views/Owner/PEdit.cshtml
@model ABSM.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm("PEdit", "Owner", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" value='@Model.ImageUrl' name="ImageValue" />
    <input type="hidden" value='@Model.ShopID' name="ShopID"/>
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "CategoryID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.ImageUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="doc" />
                @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShortDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShortDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShortDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LongDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LongDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LongDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "ListProducts")
</div>